default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: geek_dev
  username: geek_user
  password: password

test:
  <<: *default
  database: geek_test
  username: geek_user
  password: password

# production:
#   <<: *default
#   database: geek_prod
#   username: geekquery
#   password: <%= ENV["GEEKQUERY_DATABASE_PASSWORD"] %>
